version: '2.21'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER:well
      - RABBITMQ_DEFAULT_PASS:well